### ISSUE TITLE
Not able to access http url from https origin

### ISSUE THREAD

**Issue by pomdtr** [progrium/go-vscode#2]
I fixed #1  in my own fork, but I encountered a new issue:

<img width="940" alt="image" src="https://github.com/user-attachments/assets/6b43a7db-f5ff-4beb-9915-eb3e5e480ab6">

**Comment by progrium** [comment]
Wasn't expecting https so quickly! You can fix this line:
https://github.com/progrium/go-vscode/blob/main/workbench.go#L71

Like authority, it should determine the scheme from the request. I believe r.TLS?

**Comment by pomdtr** [comment]
Yeah I'm biased, I basically use https for every services using dnsmasq + caddy and local certificates

**Comment by progrium** [comment]
freak! jk
